# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       qt-components

# >> macros
# << macros

Summary:    Qt Quick UX Components
Version:    1.4.9
Release:    1
Group:      System/Libraries
License:    BSD
URL:        https://qt.gitorious.org/qt-components/qt-components
Source0:    %{name}-%{version}.tar.bz2
Source100:  qt-components.yaml
Requires:   mthemedaemon
BuildRequires:  pkgconfig(QtCore) >= 4.7.0
BuildRequires:  pkgconfig(QtGui)
BuildRequires:  pkgconfig(QtOpenGL)
BuildRequires:  pkgconfig(xrandr)
BuildRequires:  pkgconfig(xdamage)
BuildRequires:  pkgconfig(x11)
BuildRequires:  pkgconfig(contextsubscriber-1.0)
BuildRequires:  pkgconfig(maliit-1.0)
BuildRequires:  pkgconfig(mlite)
BuildRequires:  desktop-file-utils
BuildRequires:  fdupes

%description
The Harmattan Qt Quick UX Components

%package devel
Summary:    Qt UX Components Devel
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
This package is part of Harmattan Qt Quick UX Components,
it contains the development files


%package gallery
Summary:    Qt Components gallery
Group:      Development/Applications
Requires:   %{name} = %{version}-%{release}

%description gallery
Provides test applications showcasing Qt Components widgets.



%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
./configure -meego -nomake tests -xrandr -maliit -meegographicssystem
# << build pre


make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop
%fdupes  %{buildroot}/%{_libdir}

%files
%defattr(-,root,root,-)
%{_libdir}/qt4/imports/Qt/labs/*
%{_libdir}/qt4/imports/com/meego/*
%{_libdir}/qt4/imports/com/nokia/*
# >> files
# << files

%files devel
%defattr(-,root,root,-)
%{_datadir}/qt4/mkspecs/*
# >> files devel
# << files devel

%files gallery
%defattr(-,root,root,-)
%{_bindir}/QmlComponentExtrasGallery
%{_bindir}/QmlComponentGallery
%{_bindir}/TutorialApplication
%{_datadir}/applications/qmlcomponentextrasgallery.desktop
%{_datadir}/applications/qmlcomponentgallery.desktop
# >> files gallery
# << files gallery
