######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 17 19:27:14 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp

QT += svg
