######################################################################
# Automatically generated by qmake (2.01a) Thu Aug 26 22:42:30 2010
######################################################################

TEMPLATE=subdirs
SUBDIRS += calculator \
           gallery \
           pages \
           quiz \
           widgetgallery
