######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 17 23:39:37 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
CONFIG -= app_bundle
QT += svg

# Input
SOURCES += main.cpp
